# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: language statistics

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: install tree
      run: sudo apt install tree
    - name: tree
      run: tree /home/runner/work/ytPlaylistLangStats
