# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: language statistics

on:
  push:
    branches: [ "master" ]
    paths:
      - .github/workflows/contributorStatistics.yml
      - resources/*
  pull_request:
    branches: [ "master" ]
  schedule: # execute every 24 hours
    - cron: "* */24 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
    - name: load resources
      uses: actions/checkout@v4
    - name: Install cjk font
      run: sudo apt-get install fonts-noto-cjk
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Update statistics for https://www.youtube.com/playlist?list=PLdx_s59BrvfXJXyoU5BHpUkZGmZL0g3Ip
      env:
        YoutubeAPIKey: ${{ secrets.YOUTUBEAPIKEY }}
      run: |
        dotnet /home/runner/work/ytPlaylistLangStats/ytPlaylistLangStats/bin/Release/net6.0/ytPlaylistLangStats.dll download
        dotnet /home/runner/work/ytPlaylistLangStats/ytPlaylistLangStats/bin/Release/net6.0/ytPlaylistLangStats.dll stat
    - name: Update statistics for https://www.youtube.com/playlist?list=PLdx_s59BrvfVJdXVitsPHvXavY7Z-NhQx
      env:
        YoutubeAPIKey: ${{ secrets.YOUTUBEAPIKEY }}
      run: |
        dotnet /home/runner/work/ytPlaylistLangStats/ytPlaylistLangStats/bin/Release/net6.0/ytPlaylistLangStats.dll download --pl https://www.youtube.com/playlist?list=PLdx_s59BrvfVJdXVitsPHvXavY7Z-NhQx
        dotnet /home/runner/work/ytPlaylistLangStats/ytPlaylistLangStats/bin/Release/net6.0/ytPlaylistLangStats.dll stat --pl https://www.youtube.com/playlist?list=PLdx_s59BrvfVJdXVitsPHvXavY7Z-NhQx
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "nppstcc1001050311@gmail.com"
        git config --local user.name "sobel"
        git add --all
        if [ -n "$(git status --porcelain)" ]; then
           git commit -m "update language statistics" -a
           echo "{push}={true}" >> $GITHUB_OUTPUT
        else
           echo "{push}={false}" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
